spring:
  application:
    name: purchaseManagment-service
  datasource:
    url: jdbc:mysql://localhost:3306/purchasemanagment_db
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8084


resilience4j:
  circuitbreaker:
    instances:
      purchaseManagment-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      purchaseManagment-service:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - feign.FeignException$InternalServerError

  timelimiter:
    instances:
      purchaseManagment-service:
        timeoutDuration: 4s
        cancelRunningFuture: true
cancelRunningFuture: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka