spring:
  application:
    name: paymentMethod-service
  datasource:
    url: jdbc:mysql://localhost:3306/paymentmethod_db
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      paymentMethodService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      paymentMethodService:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - feign.FeignException$InternalServerError

  timelimiter:
    instances:
      paymentMethodService:
        timeoutDuration: 4s
        cancelRunningFuture: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
